= Lab 02

This is the last look at GeoQuiz. This repository includes a version of GeoQuiz as of the end of Chapter 6 with some issues.

== Create a ViewModel and a landscape layout

This version of the code does not allow the user to rotate their phone and have the correct question shown. Modify the source to fix this problem as seen in Chapter 4. You should use the ViewModel so that the activity can be torn down and recreated without losing state.

In addition, you should have a landscape layout file to handle the rotated view (you may take your work from Lab 1 to do any of this as well).

== Closing loopholes for cheaters (Book Challenge)


Cheaters never win. Unless, of course, they persistently circumvent your anticheating measures. Which they probably will. Because they are cheaters.

GeoQuiz has a major loophole. Users can rotate `CheatActivity` after they cheat to clear out the cheating result. When they go back to `MainActivity`, it is as if they never cheated at all.

Fix this bug by persisting `CheatActivity` ’s UI state across rotation and process death using the techniques you learned in Chapter 4.

== Tracking cheat status by question (Book Challenge)

Currently, when the user cheats on a single question, they are considered a cheater on all the questions. Update GeoQuiz to track whether the user cheated on a question-by-question basis. When the user cheats on a given question, present them with the judgment toast any time they attempt to answer that question. When a user answers a question they have not cheated on yet, show the correct or incorrect toast accordingly.

== Create a way to add new questions

We know how to add new activities to the app. We also know how to wire buttons to actions and modify our data store. Take these ideas together one step further and create a new button on the `MainActivity` that loads an activity to allow the user to add more questions. 

You should research the `RadioButton` / `RadioGroup` UI buttons along with the `EditText` text view for this. Along with these widgets, you should have an "Add" button that clears the widgets to their default state. Add another button that when clicked, closes the activity. Note that a call to `finish()` within the activity will return the user to the previous activity on the stack. Don't forget to use `putExtra` to add the questions and their values as the result. `PutExtra` put arrays into the result! You will need two different (equal sized) arrays to represent questions and answers, or an array of objects if those objects are serializable. Data classes ARE serializable, but the Question data class currently depends on strings already existing. You may or may not wish to modify that behavior.

== Turn in

. Commit all of these changes to this repository.
. Take screenshots of your program running and commit them to this repository.
. *Push* your code to submit.
